name: Minecraft AFK Bot

jobs:
  afk-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cài đặt Dependencies
        run: npm install

      - name: Chạy Bot AFK trong 10 phút
        # Lệnh timeout 10m sẽ tự động ngắt lệnh npm start sau 10 phút
        # '|| true' để đảm bảo workflow không bị báo lỗi khi bị timeout ngắt
        run: timeout 2m npm start || true
